### ISSUE TITLE
Contributing/bug

### ISSUE THREAD

**Issue by Oliver-Chalkley** [AdaJass/pyalgotrade3#2]
Hi, 

I'm very interested in using/contributing to this but can't get it working. I tried the first line of the tutorial but it failed:

[$ python -c "from pyalgotrade.tools import yahoofinance; yahoofinance.download_daily_bars('orcl', 2000, 'orcl-2000.csv')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/oli/virtualenvs/pyalgotrade3/lib/python3.5/site-packages/pyalgotrade/tools/yahoofinance.py", line 54, in download_daily_bars
    bars = download_csv(instrument, datetime.date(year, 1, 1), datetime.date(year, 12, 31), "d")
  File "/home/oli/virtualenvs/pyalgotrade3/lib/python3.5/site-packages/pyalgotrade/tools/yahoofinance.py", line 40, in download_csv
    return csvutils.download_csv(url)
  File "/home/oli/virtualenvs/pyalgotrade3/lib/python3.5/site-packages/pyalgotrade/utils/csvutils.py", line 62, in download_csv
    raise Exception("Invalid content-type: %s" % response_content_type)
Exception: Invalid content-type: text/html; charset=utf-8](url)

Any suggestions?

**Comment by AdaJass** [comment]
sorry, maybe it is too late to answer. hahahaha
